name: "Linter"

on:
  pull_request:

  push:
    branches: [ "*" ]

jobs:
  lint82:
    name: "Linter"
    uses: contributte/.github/.github/workflows/php.yml@v1
    with:
      name: "Linter"
      run: "vendor/bin/parallel-lint src"
      php: "8.2"

  lint83:
    name: "Linter"
    uses: contributte/.github/.github/workflows/php.yml@v1
    with:
      name: "Linter"
      run: "vendor/bin/parallel-lint src"
      php: "8.3"

  lint84:
    name: "Linter"
    uses: contributte/.github/.github/workflows/php.yml@v1
    with:
      name: "Linter"
      run: "vendor/bin/parallel-lint src"
      php: "8.4"

  lint85:
    name: "Linter"
    uses: contributte/.github/.github/workflows/php.yml@v1
    with:
      name: "Linter"
      run: "vendor/bin/parallel-lint src"
      php: "8.5"
